### ISSUE TITLE
Show verse edit Indication in all tools regardless of where the edit was performed

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5832] opened 2019-02-25 19:23 UTC
### User Story

As a user, I want the edits in one tool to be demonstrated as the pencil icon in the menu bar in another tool so that I know which verses have been edited.

### Features / Specifications

- [ ] ISSUE C: When a verse is edited in wA, the edit icon is not displayed on the verse in tW.
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by cckozie** [comment] 2019-04-25 18:19
1.2.0 (de171a2)
I made an edit in tN. The edit icon was not displayed on the verse in any of the tools.
May be related to #5837.

**Comment by cckozie** [comment] 2019-04-30 14:52
1.2.0 (f58a0ac)
Made two edits in wA, one that invalidated a tW check, and one that did not. 
In the case where the check was reset, the broken icon was displayed as expected.
In neither case did the edit icon appear on the verse in tW.

**Comment by PhotoNomad0** [comment] 2019-05-06 19:58
Fixed in issue https://github.com/unfoldingWord-dev/translationCore/pull/6039

**Comment by cckozie** [comment] 2019-05-08 15:57
Hold until all issues dealing with reset alignments and checks are completed

**Comment by cckozie** [comment] 2019-06-11 22:05
1.2.0 (9c1cf66) 
Edits made in wA are correctly indicated in tW and tN, although edits made in tW and tN are NOT correctly displayed in same tool until reloaded and are not displayed in wA. (See #6139)
Still holding.

**Comment by cckozie** [comment] 2019-06-21 19:03
Need to test to ensure that edit icon is displayed on the verse:
1.  everywhere it appears:
in wA, in tN, and in tW. In both tN and tW the verse may appear multiple times in the same category and in different categories.
2. Regardless of where it was edited:
- in the expanded scripture pane in wA, tW, and tN
- in the Check pane of tW and tN
- when edited externally

**Comment by cckozie** [comment] 2019-06-24 16:40
Unable to test external edits in 1.2.0 (cf6fd22)
Waiting on #6001 and #5686

**Comment by cckozie** [comment] 2019-07-16 13:24
Now waiting on #6168

**Comment by cckozie** [comment] 2019-07-22 15:00
2.0.0 (99b8027)
I'm consolidating all of the failures onto this issue to get the others out of Hold.
SEE ALSO #6070 AND INDICATE WHETHER THIS IS STILL A PROBLEM.

When edits are made in a tool, the alignments invalidated and selections reset alerts are all correctly displayed.

When edits are made external to tC, the alignments invalidated alert and selections reset alerts are displayed separately instead of only the alert indicating both problem. This is a problem on a different issue. (#6188)

When edits are performed in the wA expanded scripture pane, everything is good:
wA icons correct, tN icons correct, tW icons correct

ISSUE A:
When edits are performed in the tW scripture pane or check pane there are problems with the tW icons:
tW shows only broken link icons, not edit icons. tN and wA icons are correct. After loading a different project and coming back to the one edited, now both the broken link and edit icons are displayed.

ISSUE B: (may be the same problem as ISSUE A)
When edits are performed in the tN scripture pane or check pane there are problems with the tN icons:
tN shows only broken link icons, not edit icons. tW and wA icons are correct.After loading a different project and coming back to the one edited, now both the broken link and edit icons are displayed.

ISSUE C:
None of the tools any longer display the selections reset or alignments invalidated alert when the tool is opened or the user navigates to a check where the selection has been reset.

**Comment by benjore** [comment] 2019-08-01 18:27
- [ ] On Tool Launch, throw a warning that there are invalidations (reuse the verbiage that is already used). Use the message that is specific/correct for each tool. 
- [ ] No need to throw another warning when the verse/check with an invalidation is actually opened.

**Comment by PhotoNomad0** [comment] 2019-08-05 16:56
@benjore - I thought we decided this warning would be when tool is launched.

**Comment by mannycolon** [comment] 2019-08-06 19:05
Verified on 1ad7e00

**Comment by cckozie** [comment] 2019-08-06 21:58
ISSUE A:
If multiple checks have been reset do to edits in another tool, the reset selections alert is displayed multiple times when the project is loaded in the affected tool. (Actually, the first time it is displayed there is no Cancel button on it, and the second time there is a Cancel button)
This project has 3 reset checks in both tN and tW. When loaded in either of those tools, the reset selections alert is displayed, and then when it is dismissed, displayed again. (Actually the two alerts may be stacked)
The same happens if the edits are made in tW and then tN is loaded.
[en_new_phm_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3474268/en_new_phm_book.zip)

**Comment by cckozie** [comment] 2019-08-07 22:01
@PhotoNomad0 - FYI:  I found the cause of the two alerts, one shows when I load the tool, and the second shows if it opens to a check that was edited outside of the tool. 

ISSUE B:
I'm sometimes seeing the alert anytime I navigate to an edited verse, regardless of whether or that it had a selection reset or even has a selection.

ISSUE C:
In tN only, I'm seeing the reset selections alert when I navigate to the check that was reset. I thought we were now only going to display the alert when the tool is loaded, not on each verse where the selection was reset.

ISSUE D:
If I open the tool when there are reset selections, I get the alert. If I then go back to the tools page and reopen the same tool again, I do not get the alert. If I do something else in between (open another project or tool), then I do get the alert again.

ISSUE E:
Also in tN only, the checkmark remains on the menu tile after the selection was reset. This occurs if the edit is done in wA, tW, or externally.
![image](https://user-images.githubusercontent.com/8171759/62660876-f4eb2580-b934-11e9-9312-1a8f12e56ff5.png)

**Comment by cckozie** [comment] 2019-08-08 15:35
Here are the steps to replicate the last problem mentioned in ISSUE E above:
1. Import https://git.door43.org/TC_SAVE/en_new_phm_book
2. Load the project in wA
3. Edit verse 1:13 to change "gospel" to "good new"
4. Choose a reason code and click Save
5. Return to the Tools page
6. Load the project in tN
7. Open the Assume Knowledge... group
8. Note that the checkmark and selection is still on the menu tile even though the selection has been reset
9. Note also that the reset selections alert is displayed when the check is navigate to
These problems seem to only appear in tN

**Comment by PhotoNomad0** [comment] 2019-08-08 15:48
You were correct, there were two alerts stacked.

**Comment by PhotoNomad0** [comment] 2019-08-09 16:00
Verified in translationCore 2.0.0 (6da74a1)

**Comment by cckozie** [comment] 2019-08-09 20:50
2.0.0 (aca7a85)
I broke out the separate problems noted in the comments above.
ISSUE A has been fixed
ISSUE B has been fixed
ISSUE C is still a problem
ISSUE D has been fixed
ISSUE E is still a problem

**Comment by PhotoNomad0** [comment] 2019-08-12 11:45
Hmm...how did this come back?  It is now showing the edit, but not the invalidate.  looking...

**Comment by PhotoNomad0** [comment] 2019-08-12 12:41
Still a mystery how the checker and I both saw this as working, but likely due to version of tN we had loaded at time.  But looks like the cause of E is where the project had been worked on in a previous unreleased build with older tN resources (have had a few format changes in 1.2.0 to 2.0.0).  Making a fix since this could be an issue in future releases.

**Comment by PhotoNomad0** [comment] 2019-08-12 16:39
Verified in translationCore 2.0.0 (52eff0d)

**Comment by elsylambert** [comment] 2019-08-12 17:28
2.0.0 (52eff0d). Issue E is fixed. Edit made in wA which invalidated selections in tN are indicated on the Tool card. It displays Alert message that Some Selections are invalidated when tN is loaded and shows a broken link icon on the verse.

Issue C is fixed. The Alert for Invalid Selections is displayed once when tN is loaded.

**Comment by elsylambert** [comment] 2019-08-12 17:28
Not seeing Issue A, B and D.
Needs regression

**Comment by cckozie** [comment] 2019-08-12 21:43
All issues fixed in 2.0.0 (a4d181d)

**Closed as completed** 2019-08-13 15:48 UTC
Labels: QA/Pass, QA/ElsyTested
