### ISSUE TITLE
All imports hang or fail after attempting to import a usfm project that does not have an \id tag

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#4738] opened 2018-07-19 19:17 UTC
0.10.1 (b411d84)
[php_usfm_NId.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2211359/php_usfm_NId.usfm.zip)

![image](https://user-images.githubusercontent.com/8171759/42965016-5b94979a-8b5e-11e8-9225-c716229bd025.png)

The attached file is a legit usfm file except that the \id tag is missing. 
After attempting to import that file, the system hangs on all future local import attempts, and displays this error on online import attempts:
![image](https://user-images.githubusercontent.com/8171759/42965329-46c811a6-8b5f-11e8-9475-1f5adc3306d2.png)

I think the problem is that the imports folder gets deleted when the project w/o an id tag is imported.

Ideally, the project would be handled the same as one that has an invalid \id tag. If a quicker fix is to just not delete the imports folder, that will work for now and I'll create a new issue for a better fix.

**Comment by PhotoNomad0** [comment] 2018-07-20 19:42
@cckozie - taking a look using translationCore 0.10.0 (db8cd53).  It handles the file more gracefully.  Now see: 

![screen shot 2018-07-20 at 3 33 35 pm](https://user-images.githubusercontent.com/14238574/43021669-78e49b54-8c32-11e8-8472-7d7250e4839f.png)

Part of the issue is that some anonymous QA guy ;) tried importing mpg and pdf files renamed as USFM.  So the team decided to add validation to file contents to make sure this actually is a USFM file so as not to crash the USFM parser.  It was decided that as a minimum that a USFM file needs to have an \id and a \h.  Probably we can re-address this later, but I am reluctant to take out the checks without a consensus and a better solution.

**Comment by cckozie** [comment] 2018-07-20 19:48
@PhotoNomad0 Yes, I know that the problem on the bad file is handled gracefully. But after encountering that error, no further imports will succeed.

**Comment by PhotoNomad0** [comment] 2018-07-30 22:28
@cckozie - this seems to be fixed as of translationCore 0.10.0 (c12e5e6) - subsequent USFM imports are working.

**Closed as completed** 2018-08-10 18:45 UTC
Labels: QA/Pass
