### ISSUE TITLE
Don't drop it here symbol

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#3638] opened 2018-01-10 00:57 UTC
ENHANCEMENT SUGGESTION -

The Don't symbol that appears when moving an alignment card is another good metaphor/sign for proper placement of the word card. 

But, it would be nice if the metaphor was also used when the end-user tries to drop an alignment card (black biblical language card) onto the next card. If you see the interaction - the card on the right has where the dotted outline does turn blue (in the bottom portion) giving the impression that the card can be moved to this spot. And the Don't symbol is not shown. It cannot be moved/dropped there. 

See what I mean in this 1 min video. https://youtu.be/wv_Q3fK3jsA

When I tried to move the biblical language card to a row below - the Don't symbol appears AND the dotted-outline does not turn blue.

**Comment by jag3773** [comment] 2018-01-10 15:00
I think this is a duplicate of #3534 .  Thank you for the feedback @ChrisJarka .  I'll add you're comment to that other issue.

**Closed as completed by jag3773** 2018-01-10 15:00 UTC
Labels: Reviewed/Duplicate, Kind/Feedback
