### ISSUE TITLE
Gateway Languages are displayed and the wrong message is displayed for tN Launch button when there are no corresponding tN's

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6174] opened 2019-06-25 17:57 UTC
#1.2.0 (f134cbf)
[en_ultt_jdg_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3326877/en_ultt_jdg_book.zip)

1. When online projects for OT Books are imported:For e.g. Judges(ceb & en) & Joshua(ble), the disabled Launch button for tN displays a message "You must select a Category to launch this tool" in oppose to "Book not supported" as in tW. 
@benjore - Is "Book not supported" really the correct message?
![tN Lauch button.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/d7779df1-4010-43ce-a645-028971a14332)

The message displayed in the popup should be the same as the one shown for tW. No categories are shown on the tN tool card since none exist for the book and language, so the user cannot select any cagtegories.

2. It should not display the GL selection list as the resources are not available for the GL. Instead it should display "None available" as in tW

## Specs

- [ ] For a GL to show up in the dropdown it needs: 
  - [ ] tN TSV file for that book
  - [ ] Aligned book in the GL for the selected project
  - [ ] tA for that GL

**Comment by benjore** [comment] 2019-06-26 20:54
![image](https://user-images.githubusercontent.com/13352518/60214188-9f4a3600-982a-11e9-999d-76646a10e796.png)

This is a screenshot of the desired behavior.

**Comment by PhotoNomad0** [comment] 2019-07-09 12:36
@benjore - for clarity here: we want to have the message "book not supported" take priority over needing to select category, correct?

**Comment by PhotoNomad0** [comment] 2019-07-11 17:37
Verified in translationCore 1.2.0 (a46fac1).

**Comment by elsylambert** [comment] 2019-07-12 15:44
Verified in  1.2.0 (70f669f). 
![tN message](https://user-images.githubusercontent.com/51806180/61140912-6355d880-a49a-11e9-81a1-8895c4a086eb.png)
Working fine. For a Project for which the resources are not there, GL shows as None available and "Book not supported" for the Launch Button.

**Comment by cckozie** [comment] 2019-07-15 23:07
Looks good in 1.2.0 (736956e)

**Comment by cckozie** [comment] 2019-07-25 15:50
2.0.0 (00bca0b)
This problem has reoccurred or was never completely fixed.
Here are the defined tN Hindi resources (they are the same for all groups):
![image](https://user-images.githubusercontent.com/8171759/61888536-458c6880-aec9-11e9-827a-39b6481c4f3c.png)

When I load a 1TI project the tN tool card shows Hindi as an available GL. No categories are displayed, but the Launch button is enabled and checks are shown when the project is loaded.

**Comment by PhotoNomad0** [comment] 2019-07-29 23:15
Verified in translationCore 2.0.0 (64f2de6)

**Comment by elsylambert** [comment] 2019-07-30 15:07
I imported hi_1th_book project which does not have hindi resources. So for tN in the GL drop-down Hindi is not available to be selected. Thats fine, but it shows English available as GL, 
When I opened it with en as GL, see below snapshot of tN:
![image](https://user-images.githubusercontent.com/51806180/62140979-db553880-b2b9-11e9-8274-775217c2713f.png)

For tW got critical error:
![Error-6174](https://user-images.githubusercontent.com/51806180/62141053-f9229d80-b2b9-11e9-9244-1f8175cdefaa.jpg)
![error2-6174](https://user-images.githubusercontent.com/51806180/62141066-fe7fe800-b2b9-11e9-96d8-f19417f04097.jpg)
Here are the logs:
[Tue Jul 30 2019.zip](https://github.com/unfoldingWord-dev/translationCore/files/3447437/Tue.Jul.30.2019.zip)

Here is the project:
[hi_irv_1th_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3447442/hi_irv_1th_book.zip)

**Comment by PhotoNomad0** [comment] 2019-07-30 18:50
this is a duplicate of https://github.com/unfoldingword-dev/translationcore/issues/6289

addressed in translationCore 2.0.0 (cd0f9f1)

**Comment by cckozie** [comment] 2019-07-30 22:05
The original problem does not appear in 2.0.0 (cd0f9f1). The Critical Error message is no longer a problem either. The bad text shown in the Hindi 1TH problem is because of the extra asterisks.

**Comment by elsylambert** [comment] 2019-07-31 13:53
Looks good in 2.0.0 (bd37460). When tN resources for a Book are not available, that GL is not available under GL drop-down.

**Closed as completed** 2019-08-13 15:38 UTC
Labels: Kind/Bug, QA/Pass, QA/ElsyTested
