### ISSUE TITLE
target language word highlighting error & suggestion

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#637] opened 2017-02-06 16:36 UTC
I tried to highlight the target text and could not highlight all the desired words.

BTW - it is painful to click on each word instead of using a click-hold-drag action.

https://youtu.be/oR3h-I78TXM

**Comment by benjore** [comment] 2017-02-09 17:10
Duplicate of #673

**Closed as completed** 2017-02-09 17:10 UTC
Labels: Reviewed/Duplicate
