### ISSUE TITLE
Bookmark in side menu not matching up with toggle in tW tool

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5262] opened 2018-10-17 21:38 UTC
It has happened a couple times now, but I'm having some problems reproducing it. I think it has to do with changing between tools. There are times when the bookmark functionality in the side menu is exactly opposite of what it should be. Toggling the bookmark off turns it off in the `Step 2. Check` header bar, but turns it on in the side menu. And toggling the bookmark on turns it on the header bar but off in the side menu. 

![Screen Shot 2018-10-17 at 4.32.21 PM.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/aa1737c4-560e-45bf-afac-8e4109874bf6)

**Comment by cckozie** [comment] 2019-02-21 19:08
1.1.3 (240da43) 
This is still an intermittent problem. No errors in the console, but the icon on the verse sometimes is out of step with the one in the status bar and the bookmark switch on these two verses. As mentioned above, turning the switch off now turns the verse tile icon on and vice versa. 
It also sometimes fails when turning the bookmark switch off. The icon in the status bar goes off, but the one in the menu stays on.
It's not easy to replicate. I was running a script that sets the bookmark using the switch, then tests to see that the two icons agree with the bookmark switch. Since I was not changing tools, I do not think it is related to that.
After reloading the project, the problem is sometimes fixed and they are in sync again. Attached is a project with the problem in many verses. (Click on the bookmark filter. I think all of the groups have verses where the icons are out of sync)
[en_ult_1jn_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2896308/en_ult_1jn_book.zip)

![image](https://user-images.githubusercontent.com/8171759/53276471-c0581a00-36c4-11e9-8073-177395740971.png)

![image](https://user-images.githubusercontent.com/8171759/53276445-a1598800-36c4-11e9-83ba-080d3e2d212d.png)

The menu filter keys off of the icon on the verse tile.
![image](https://user-images.githubusercontent.com/8171759/53276655-ab2fbb00-36c5-11e9-836d-3734809e4fc1.png)

**Comment by cckozie** [comment] 2019-03-18 23:19
This now appears to have been fixed in 1.1.3 (64d8fb7)

**Closed as completed by cckozie** 2019-03-18 23:19 UTC
Labels: Kind/Bug
