### ISSUE TITLE
Add USFM3 Support

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#2914] opened 2017-10-12 18:36 UTC
## User Story

As an aligner, I want to be able to upload my alignment data as USFM3 so that I can get it in the API and bring it back (eventually) into the tC app. 

## Specs
- [ ] Include Selection data in the USFM3 alignment file such that it can seed the Alignment Tool. 
- [ ] `Upload to Door43` - this needs to upload all checking data as it currently is & include alignment data in USFM3 format
  - [ ] Put alignment data in the root of the project
- [ ] Local `Export Alignment Data as USFM3`
- [ ] Add support for importing a USFM3 source from API
- [ ] Add support for importing a USFM3 target from DCS
- [ ] Reference for data structure: https://github.com/unfoldingWord-dev/translationCore/wiki/Alignment-Data-Structure:-USFM-3

**Comment by RoyalSix** [comment] 2017-11-01 18:15
- alignment data only

**Comment by klappy** [comment] 2017-11-03 18:54
Via #3027, here are the requirements to get this story accomplished.


## Expanding USFM 3 support
The following changes are needed as there are many dependencies for these changes. Maintaining punctuation and non-word markers such as footnotes via Verse Objects allows us not to lose any data while importing/exporting USFM 3. This ensures all data in the original USFM 2 files are able to be preserved and not lost.

USFM imports to tC have data/markers that occurs outside of a verse and are not currently preserved in any way. We don't currently have a use case for them inside of tC other than upon export. In order to preserve them upon export, we need to send the original imported USFM file to the JSON to USFM converter to preserve everything not in a verse, as the verse should already preserve what was imported.

There are no known blocking dependencies to start working on this.

- Maintain punctuation and non-word markers such as footnotes via Verse Objects
  - Preserve punctuation and non-word markers in USFM parsing via Verse Objects
  - Support punctuation and non-word markers in USFM generation via Verse Objects
  - Preserve data/markers outside of verses from an imported USFM file

## GL Alignment Data from DCS API via USFM 3
The following changes are needed once the USFM.js library preserves and supports parsing/generating USFM 3 text/punctuation outside of word markers. It is dependent on the changes to the USFM.js library.

- GL Alignment Data Export from tC as USFM 3
  - tC Helpers: Combine Target Verse String and Alignment Data to Verse Objects
  - USFM.js: Verse Objects to USFM 3 conversion
- GL Alignment Data Import from DCS as USFM 3
  - USFM.js: Improved USFM 3 to Verse Objects
  - tC Helpers: Split Verse Objects to Target Verse String and Alignment Data
- GL Aligned Bibles Import to tC_Resources
  - tC_Resources: Convert USFM 3 GL Aligned Bibles to Verse Objects
  - tC_Resources: Store GL Aligned Bibles as Verse Objects
- DCS Upload of Alignment Data as USFM 3 file in root
  - tC Actions: Snapshot USFM 3 to project root prior to uploading to Door43

**Comment by jag3773** [comment] 2017-11-15 16:13
Duplicate of #3184

**Closed as completed by jag3773** 2017-11-15 16:13 UTC
Labels: Reviewed/Duplicate
