### ISSUE TITLE
In wA: Clear "activated" (blue) words when navigating away from alignment pane

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5930] opened 2019-03-28 14:00 UTC
## Description

- Problem 1: "blue" words carry across verses (v.1.1.2)
  - Select multiple words in the word bank (so that they turn blue). 
  - While they are still blue, navigate to a new verse,  in the new verse the words in the same position will be "blue" (even if they have already been used)
  - (Example: Open a project, go to 1:1. Make the first 5 words blue. Navigate to 1:2. Notice the first 5 words are blue. Make the next 5 words blue. Navigate to 1:3. Notice that the first 10 words are now blue.)

- Problem 2: "blue" words can be disabled when navigating to Expanded Scripture Pane/Edit, necessitating restart to enable them again (Reported by Larry, I was unable to reproduce). 

## Solution

- [ ] If a user has "blue" words and then clicks anything that opens a modal, deselect these words. 
- [ ] If a user has "blue" words and then navigates to a new verse, deselect these words.

**Comment by cckozie** [comment] 2019-04-03 18:46
See also #5175

**Comment by cckozie** [comment] 2019-07-16 14:08
1.2.0 (9f6a878)
Other instances where the tiles are not unselected: (@benjore says these should be fixed)
1. Clicking Refresh, Accept, or Reject
![image](https://user-images.githubusercontent.com/8171759/61301142-f21f6980-a7a8-11e9-807c-ba73166dbc7f.png)
2. Setting Alignment Complete to On or Off
![image](https://user-images.githubusercontent.com/8171759/61301280-3ad72280-a7a9-11e9-83ef-cac6dec42f9a.png)

**Comment by cckozie** [comment] 2019-07-22 16:27
2.0.0 (99b8027) 
I  am passing this since both 1. and 2. noted above have been fixed.

However, I am noting other (non-specified in requirements) actions that cause the words to be de-selected):
1. Merging Greek words
2. Moving an aligned target word
3. Moving a suggested word

And other (non-specified in requirements) actions that do not cause the words to be de-selected):
1. Clicking on a suggested word to accept it
2. Clicking on the X on a suggested word to reject it.
3. Opening the Actions menu

**Comment by elsylambert** [comment] 2019-07-22 16:51
Verified in 2.0.0 (99b8027). Selected words(Blue) in wA are deselcted in the following cases:
1. Click on "Refresh".
2. Toggle On/Off Alignment complete button.
3. Move to another verse.
4. Click on the Expanded Scripture Pane.
5. Going back to tools page.
Not seeing any issues.

**Closed as completed** 2019-07-30 18:41 UTC
Labels: QA/Pass, Priority/High, QA/ElsyTested

**Comment by cckozie** [comment] 2019-08-01 18:49
Needs regression
