### ISSUE TITLE
Move all authentication tokens into a single file. 

### ISSUE THREAD

**Issue by ihoegen** [unfoldingWord/translationCore#18] opened 2016-08-11 14:23 UTC
As a developer, I want a centralized place to store my authentication tokens, so that I may have easy setup.

**Comment by ihoegen** [comment] 2016-08-11 15:56
Refereneced in #15

**Comment by klappy** [comment] 2016-08-12 16:46
What do you guys think of keeping things in the Review column until I sign off on them. Reserve the Done column for QA or Product Owner?

**Comment by klappy** [comment] 2016-08-12 16:57
NM, That's what closed is for, I don't want to add any unnecessary layers/steps.

**Comment by klappy** [comment] 2016-08-12 16:58
Is this a duplicate of #15?

**Comment by RoyalSix** [comment] 2016-08-12 17:06
Yea I think that's why it got closed.

**Closed as completed** 2016-08-23 22:28 UTC
