### ISSUE TITLE
Localized UI

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#3765] opened 2018-02-12 15:53 UTC

**Comment by jag3773** [comment] 2018-02-12 20:14
Isn't this a duplicate of https://github.com/unfoldingWord-dev/translationCore/issues/2003 ?

**Comment by benjore** [comment] 2018-02-12 20:16
@jag3773 Yes, but #2003 doesn't show up on the roadmap. For a quick workaround for our meeting, I added this one. 

In a perfect world, roadmap stories that are progressing through the "Work-in-Progress" pipelines would show up on the roadmap.

**Comment by PhotoNomad0** [comment] 2018-04-02 13:11
@benjore - what remains to be done here that isn't in https://github.com/unfoldingWord-dev/translationCore/issues/4125?

**Comment by benjore** [comment] 2018-04-04 14:53
This is only a placeholder for the Roadmap label.

**Closed as completed** 2018-04-12 02:15 UTC
Labels: Roadmap
