### ISSUE TITLE
We should allow users to change the name of their projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#2552] opened 2017-08-25 23:24 UTC
We should provide the ability for the user to give the project meaningful names both at the time of import and anytime later.

**Comment by benjore** [comment] 2017-09-15 18:16
Repo name needs to change as well. 
Retain repo history. 
Add tests: renaming the project & new repo for Door43.

**Comment by jag3773** [comment] 2017-11-13 19:09
Duplicate of #2546 .

**Closed as completed by jag3773** 2017-11-13 19:09 UTC
Labels: Reviewed/Duplicate, Kind/Enhancement
