### ISSUE TITLE
Handle General Notes in tN

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#464] opened 2017-01-10 21:01 UTC
tN: There are many notes that do not have links to tA articles, which are leveraged as categories/grouping of note checks. To handle the notes without a link to tA, we can categorize them or group them into "General" Notes.

**Comment by benjore** [comment] 2017-02-09 19:31
Duplicate of #246

**Closed as completed** 2017-02-09 19:31 UTC
Labels: Reviewed/Duplicate
