### ISSUE TITLE
Metaphor Action in Alignment Tool

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord/translationCore#3637] opened 2018-01-10 00:35 UTC
ENHANCEMENT SUGGESTION -

The end-user might find it easier to move a card off of a combined card to a stand alone card if the gray in between space holder would turn all blue instead of just the bracket on the gray space holder.
If the end-user is on a smaller screen they might not realize that there is an icon that turns blue (as the indicator that the word card is in the correct space) under the card being moved. See the video https://youtu.be/Pgk9I9qsV7I 

Here is a screen shot with the suggested change.

![back the bar blue](https://user-images.githubusercontent.com/9850185/34750169-a09ea9e2-f573-11e7-8d27-b549a30abe0e.png)

**Comment by jag3773** [comment] 2018-01-10 15:03
Duplicate of #3534 .

**Closed as completed by jag3773** 2018-01-10 15:03 UTC
Labels: Reviewed/Duplicate, Kind/UserExperience, Kind/Feedback
