### ISSUE TITLE
When user selects to rename the repo on a Door43 import, the repo gets renamed but the manifest doesn't get updated

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#6508] opened 2019-10-22 20:50 UTC
2.0.0 (f5ff634) 
I think this has been a problem for a long time.
1. Download a project from your own D43 repo
2. On the project details screen, change the translation id
3. When the copy or rename repo alert is displayed, choose Rename
4. Look at the renamed repo on Door43. Note that the manifest file still indicates the original translation id
5. Import the renamed project. Note that on the project details screen it still shows the original translation id

**Comment by PhotoNomad0** [comment] 2019-10-29 13:18
@cckozie - it is looking like the manifest in the project is being updated on the local PC, but we are not automatically pushing the latest change up to D43.  Looking into fixing that.

**Comment by PhotoNomad0** [comment] 2019-10-30 11:58
This will be fixed in https://github.com/unfoldingWord/translationCore/pull/6514

**Comment by PhotoNomad0** [comment] 2019-11-11 20:02
Verified that Changes are in translationCore 2.1.0 (d8f36fe)

**Comment by cckozie** [comment] 2019-11-12 15:04
2.1.0 (d8f36fe)
When I follow the first 3 steps in the first comment I always receive the "The Door43 repository was not renamed." alert. The requested repo name does not exists on D43.
If I choose the Create New Repository option on the project renamed alert, I always receive the "The Door43 repository could not be created." alert. The requested repo name does not exists on D43.

**Comment by PhotoNomad0** [comment] 2019-11-13 11:41
@cckozie - having trouble reproducing this one.  Do you have a log file I can look at?

**Comment by PhotoNomad0** [comment] 2019-11-13 11:46
@cckozie - I did find that it was doing a double push to DCS - certainly inefficient, but not seeing the error.

**Comment by cckozie** [comment] 2019-11-13 16:23
@PhotoNomad0 Here's a video and log
[Tue Nov 12 2019.log.zip](https://github.com/unfoldingWord/translationCore/files/3842262/Tue.Nov.12.2019.log.zip)
[6508.mp4.zip](https://github.com/unfoldingWord/translationCore/files/3842268/6508.mp4.zip)

**Comment by PhotoNomad0** [comment] 2019-11-13 16:23
@cckozie - I know I should wait for more info, but I have a test build to try. Has cleanup of double push to DCS, also fix to cases where DCS did not have updated manifest contents.

From the `release-vx2.1.0-test` branch:
[Linux build 2.1.0 (34acf40)](https://tc-builds.door43.org/build/release-vx2.1.0-test/translationCore-linux-x64-2.1.0-34acf40.deb) is ready for download.
[macOS build 2.1.0 (34acf40)](https://tc-builds.door43.org/build/release-vx2.1.0-test/translationCore-macos-x64-2.1.0-34acf40.dmg) is ready for download.
[Windows x64 build 2.1.0 (34acf40)](https://tc-builds.door43.org/build/release-vx2.1.0-test/translationCore-win-x64-2.1.0-34acf40.setup.exe) is ready for download.
[Windows x32 build 2.1.0 (34acf40)](https://tc-builds.door43.org/build/release-vx2.1.0-test/translationCore-win-x32-2.1.0-34acf40.setup.exe) is ready for download.

**Comment by cckozie** [comment] 2019-11-13 17:01
@PhotoNomad0 I'm seeing the same problems in 2.1.0 (34acf40) 
Oh wait! Thinking through why it might always fail for me but not for you, was reminded of my "Login become invalid message". So I tried an upload to Door43 and got that message. Logged out and back in, now the upload succeeds, and the repo rename also succeeds. 
Maybe we should try to figure out the invalid login thing, or present that message under those circumstances on any attempt to access Door43. Thoughts?

**Comment by PhotoNomad0** [comment] 2019-11-13 17:21
@cckozie - I was going to ask you about the login because of 401 error in the log file.  I haven't seen the invalid login very much - but usually seems to happen when I accidentally run to instances of tC at the same time (have the built app still running when I launch tC from developers environment).  THe other time was testing Rich's development server.

Maybe we recheck the credentials before downloads (if they are not a local user).  ~May not be simple to check.  I saw a 401 error when trying to get a repo list, but there could be other reasons for that.  A good standup topic.~ I'll see how upload checks it.

**Comment by PhotoNomad0** [comment] 2019-11-13 17:24
@cckozie - will also need to check login when user renames the project.

**Comment by PhotoNomad0** [comment] 2019-11-14 17:47
Verified in translationCore 2.1.0 (c06cc80)

**Comment by cckozie** [comment] 2019-11-14 17:49
Works in 2.1.0 (c06cc80)

**Closed as completed** 2019-12-19 20:30 UTC
Labels: Kind/Bug, QA/Pass
