### ISSUE TITLE
UGNT: Import proposed Greek in USFM 3

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2259] opened 2017-07-24 23:18 UTC
Via Wiki: https://github.com/unfoldingWord-dev/translationCore/wiki/Greek-Hebrew-Ideal-Format:-USFM-3

## Tasks
- [Blocking] UGNT USFM 3 exposed via DCS v3 API.
- [13] Write download/import script for Greek USFM 3 in DCS v3 API.
- [8] Package download/import script to be run as an NPM script.

**Comment by benjore** [comment] 2017-08-10 16:10
Initial SPIKE for the data structure #2122

**Comment by benjore** [comment] 2017-09-08 15:13
Here is the file to be used for Titus:

https://team43.slack.com/files/jag3773/F6P9SC58A/57-tit.usfm

**Comment by klappy** [comment] 2017-09-11 18:04
From this point on, the Greek will only include Titus. (Until we have more data)

**Comment by jag3773** [comment] 2017-11-14 20:07
duplicate of #3104 and #2143 .

**Closed as completed by jag3773** 2017-11-14 20:07 UTC
Labels: Reviewed/Duplicate, Epic
