### ISSUE TITLE
Update version failed

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#7438] opened 2022-10-05 20:12 UTC
1. Import this project: [https://app.zenhub.com/files/65028237/706ce4e8-1101-491b-973b-4e7c0cc3f72b/download](https://app.zenhub.com/files/65028237/706ce4e8-1101-491b-973b-4e7c0cc3f72b/download)
2. Download source content for test_org2(ml) 
3. Open wA tool with test_org2(ml)
4. Align a few verses.
5. Do an Export to USFM with alignments of this project.
6. Now, import locally the same USFM from step 5 and open the project.
7. Open the project from step 5, it shows that the project was aligned with a newer version.
 ![Screen Shot 2022-10-05 at 4.06.31 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/1cecf0c4-5a5c-454d-9835-a3589f90bbe1)
8. click on Update version. It gives the error that the update failed.
![Screen Shot 2022-10-05 at 12.02.16 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/5b9ad09c-2e7c-4c30-97ec-f52bf3f13331)

Log file: 
[Wed Oct 05 2022.log.zip](https://github.com/unfoldingWord/translationCore/files/9718709/Wed.Oct.05.2022.log.zip)

**Comment by PhotoNomad0** [comment] 2022-10-05 21:12
@elsylambert This is a great edge case test!  When we import a project using USFM, there is no history, so there should not be this warning.

**Comment by PhotoNomad0** [comment] 2022-10-06 00:29
Cannot reproduce this in latest build translationCore 3.4.0 (e1f61af)

**Comment by elsylambert** [comment] 2022-10-06 12:57
@PhotoNomad0 I can reproduce this issue in translationCore 3.4.0 (e1f61af) .
![update version](https://user-images.githubusercontent.com/51806180/194318592-18ee367d-8a9e-40b2-bc9c-6d6e4f7c2335.png)

Latest Log file: 
[Thu Oct 06 2022.zip](https://github.com/unfoldingWord/translationCore/files/9725009/Thu.Oct.06.2022.zip)

**Comment by PhotoNomad0** [comment] 2022-10-06 16:42
@elsylambert Issue fixed in translationCore 3.4.0 (5b601bd)

**Comment by elsylambert** [comment] 2022-10-06 20:12
Not seeing this issue in translationCore 3.4.0 (5b601bd). Able to open imported project with alignments.

**Closed as completed** 2022-10-12 12:42 UTC
