### ISSUE TITLE
Initial startup of tC takes too long

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1990] opened 2017-06-28 14:56 UTC
On my WIndows field machine it takes 3 1/2 minutes to start tC the first time. We need to either dramatically reduce the startup time or display informational messages and progress bars during the initial load.

**Comment by benjore** [comment] 2017-06-29 16:20
@cckozie and Ben : What is acceptable?

**Comment by cckozie** [comment] 2017-06-30 16:08
@benjore I'd like to see something in the neighborhood of 15 seconds. Again, this is a first impressions kind of issue. I think it is also necessary to display some information to the user during this process about what is happening similar to the way we did it in tS. (Loading UI, Loading project list, etc.) I'm not sure what would be applicable to tC, maybe Loading ULB..., Loading UDB..., Loading UGNT, etc. A progress bar for each message would be a nice to have.

**Comment by jag3773** [comment] 2017-12-07 17:48
Duplicate of #2945

**Closed as completed by jag3773** 2017-12-07 17:48 UTC
Labels: Reviewed/Duplicate
