### ISSUE TITLE
Importing first project after install fails for lack of imports folder

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord/translationCore#4724] opened 2018-07-17 20:53 UTC
### User Story
Immediately after an install, I attempted to import a project. It would fail everytime until I created an "imports" folder.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

**Comment by PhotoNomad0** [comment] 2018-07-20 01:06
Duplicate of #4731

**Closed as completed** 2018-07-20 16:24 UTC
