### ISSUE TITLE
App misbehaves after clicking Select on a project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#1331] opened 2017-04-28 13:51 UTC
If I select an eph or tit project it just sits on the projects screeen
If I select a non-eph or tit project, it displays the "You can only load..." message.
Clicking the Close button does nothing.
Clicking on one of the other tabs or options does nothing. I'm stuck on the projects screen.

I recreated the problem by reloading tC then, 
1. select a project and tW, 
2. make a selection on a check, 
3. click on Project
4. choose a different project and same tool as in step 1
5. repeat steps 3 and 4
6. click on the project from 1 and witness the problem described.

Here's the console log:
[log.txt](https://github.com/unfoldingWord-dev/translationCore/files/964484/log.txt)

**Comment by EllDoubleYew** [comment] 2017-04-28 20:07
To add to some of my findings on this:

The error is caused by groupsDataReducer in one of its toggle actions. 

The action getToggledGroupData is getting a state of undefined by something. I cant quite figure out what it is. 

Worse case scenario groupData does not exist we just don't run this function. But then again group data should exist 🤔

There may be something more to this, something eating the group data which would be bad.

**Comment by EllDoubleYew** [comment] 2017-04-28 20:09
I have a fix for this particular issue that was trivial. I just check to see if groupData exists before attempting to make any changes to its data. But I am worried something else is going on that would be giving the groupData reducer an undefined data. 

I could just push the fix and call it quits but I am not sure if that is the best idea. What do you think @benjore ?

**Comment by cckozie** [comment] 2017-05-01 17:01
@EllDoubleYew - @benjore asked me to take a look at this. Without understanding any more about this, it seems to me that undefined data would most likely indicate a problem somewhere else. I'd suggest bringing this up in one of the dev meetings to see if anyone has an idea on why that condition exists.

**Closed as completed** 2017-05-18 18:47 UTC
Labels: Kind/Bug, QA/Pass, Priority/Critical
