### ISSUE TITLE
Enhancements to "checking for invalidation"

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5941] opened 2019-04-02 14:26 UTC
This is a follow-up to #3562 

- [x] Change the verbiage in the pop-up with the spinner from `Doing Invalidation Checking` to `Checking if this edit conflicts with saved selections and alignments...`
- [x] Only show one dialog at a time (i.e. when the spinner is on the screen, don't have another dialog show up behind it. 
- [x] Create a new dialog for if BOTH alignments and selections have been invalidated. Verbiage, "Changes have been detected in your project which have invalidated some selections and some alignments. These verses display an icon of a broken chain next to the reference in the side menu." 
  - [x] In this way, only one dialog will ever show up after the spinner is done spinning.

**Comment by cckozie** [comment] 2019-04-24 16:31
@benjore - It is not specified in this issue, but there is no longer an option for "Do not show again" when alignments get invalidated. 
1. Should I fail this issue for that?
2. Should the option to not show again be shown regardless of whether it's selections that have been reset, alignments invalidated, or both?

**Comment by benjore** [comment] 2019-04-24 19:31
1. The "Do not show again" needs to remain for invalidated alignments. Fail it. 
2. Only alignments invalidated at this time.

**Comment by cckozie** [comment] 2019-04-25 15:54
@benjore - Does the fact that we now have the "do not show..." checkbox on the "Some selections..." alert displayed when (re)importing a project change your mind about 2. above?
![image](https://user-images.githubusercontent.com/8171759/56750002-76cd8f00-6748-11e9-83d8-22cb56c4f78e.png)

**Comment by benjore** [comment] 2019-04-25 16:05
Yes it does. I didn't realize we had implemented that already.

**Comment by cckozie** [comment] 2019-04-25 16:08
1.2.0 (de171a2)
Need to implement the "Do not show this warning again" checkbox option on all notifications of reset selections, invalidated alignments, and both.
(Yes, it probably should have been spelled out on the requirements)

**Comment by PhotoNomad0** [comment] 2019-04-29 13:04
@benjore - How do you want the behavior on the combined warning?  Do you want to combine the do not shows checkboxes for alignments and selections?  Do you want separate check boxes?

**Comment by PhotoNomad0** [comment] 2019-04-30 14:30
@benjore - Also should this be fixed in 1.1.4 since it is a high priority for Larry.

**Comment by benjore** [comment] 2019-04-30 19:57
One checkbox for both is fine. Larry doesn't do anything in tW, so I don't think he'll have any problem with this. 1.2 is fine. (Assumption: the checkbox for invalidations for only alignments still works as per usual.)

**Comment by PhotoNomad0** [comment] 2019-05-01 12:03
@benjore - ~note this is also broken now when editing in WA, when I consolidated the prompts.  So I strongly suggest fixing this in 1.1.4.~

Nevermind - after checking I discovered that we did not consolidate dialogs in 1.1.4

**Comment by cckozie** [comment] 2019-05-08 15:29
1.2.0 (1612995) (probably related to #5832 and #6001)
[en_test_1ti_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/3158012/en_test_1ti_book.zip)
This project is fully aligned and has one tN check completed and one tW check completed.
1. Load the project in wA
2. Edit verse 1:3 to change the word "doctrine" to "theology". This will invalidate the alignment and the tN check.
3. Select a reason code and click Save
4. **ISSUE A:** **FIXED IN 1.2.0 (2372490)** Note that the alignments invalidated alert is displayed, but not the selections reset alert.
5. Edit verse 1:20 to change the word "taught" to "told". This will invalidate the alignment and the tW check.
6. Select a reason code and click Save
7. **ISSUE B:**  **FIXED IN 1.2.0 (2372490)** Note that the alignments invalidated alert is displayed, but not the selections reset alert.
8. Return the the Tools page
9. **ISSUE C:**  **FIXED IN 1.2.0 (2372490)** Note that the wA card correctly indicates 2 broken alignments, but neither the tN or tW card indicate and reset selections.
10. Load the project in tN
11. **ISSUE D:**  **FIXED IN 1.2.0 (2372490)** Note that the alert indicating reset selections is not displayed.
12. **ISSUE E:** **FIXED IN 1.2.0 (2372490)** Note that verse 1:3 under Assumed Knowledge... indicates a broken link, but the selection is still displayed on the menu tile. 
13. **ISSUE F:**  **FIXED IN 1.2.0 (2372490)** Note also that only the broken link icon is shown when both it and the edit icon should be shown on a hover over. (I can move this one to #5832 if you'd prefer)
14. **ISSUE G:**  **FIXED IN 1.2.0 (2372490)** Note also that even though the text on the menu tile shows the ellipsis, that the hover over to display the full text does not work.
15. Load the project in tW
16. Note that the alert indicating reset selections is now displayed.
17. Note that verse 1:20 under blasphemy indicates a broken link and also an edit when hovered over

**Comment by RoyalSix** [comment] 2019-05-13 15:13
On build number 521546

Issue A: The alert I am seeing says `Changes have been detected in your project which have invalidated some selections and some alignments. These verses display an icon of a broken chain next to the reference in the side menu.` So I am assuming that is fixed now.

**Comment by RoyalSix** [comment] 2019-05-14 05:46
Progress:
- A, B, C, D, E, F

**Comment by cckozie** [comment] 2019-06-12 23:19
1.2.0 (2372490)
I followed the steps 1-17 above, and everything looked good. I then proceeded with the following steps, and found a problem similar to ISSUE E above.
18. Load the project in wA.
19. Edit verse 1:4 to insert the word "any" before the word "attention".
20. Select a reason code and click Save
21. Return to the Tools page
22. Load the project in tN
23. Navigate to verse 3:13 in the Assumed Knowledge and Implicit Information group
24. Select the words "in good standing" and click Save
25. Click Save & Continue
26. Return to the Tools page
27. Load the project in wA
28. Edit verse 3:13 to change the word "standing" to "place"
29. Select a reason code and click Save
30. Return to the Tools page
31. Load the project in tN
ISSUE H: **Fixed in 1.2.0 (7caed9f)** Note that on verse 3:13 the previously made selection is still displayed on the menu tile.
ISSUE I: **Fixed in 1.2.0 (7caed9f)** Note that the checkmark is being displayed instead of the broken link icon on both the menu tile and in the hover over.

**Comment by RoyalSix** [comment] 2019-06-19 17:15
May be fixed by #6000

**Comment by RoyalSix** [comment] 2019-06-21 00:37
daee8ab

**Comment by cckozie** [comment] 2019-06-21 17:54
Looks good in 1.2.0 (7caed9f)
Needs regression

**Closed as completed** 2019-07-02 18:24 UTC
Labels: QA/Pass
