### ISSUE TITLE
UGNT Scripture Pane Alignment

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#2261] opened 2017-07-24 23:34 UTC
Via Wiki: https://github.com/unfoldingWord-dev/translationCore/wiki/translationWords-based-on-Greek-Strong's-Workflow

### Prepare tC ScripturePane for new highlighting via tW Selections.
1. Update tC to import alignment and selections data.
    - [Blocking] English ULB USFM 3 for alignments to be exposed in DCS v3 API.
    - [13] Update tC resources reducer to include alignment data from USFM 3 word markers.
2. Update tC Scripture Pane to highlight reference Bibles with alignment data.
    - [13] Highlight Greek occurrence based off of tW check data.
    - [21] Highlight the GL occurrence based off of linking to Greek occurrence.

**Comment by jag3773** [comment] 2017-12-20 15:17
Duplicate of #3196

**Closed as completed by jag3773** 2017-12-20 15:17 UTC
Labels: Reviewed/Duplicate, Epic
