### ISSUE TITLE
Ignore non-Bible book USFM files

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6746] opened 2020-03-10 17:40 UTC
Extra files, such as front matter, like A0-FRT.usfm (https://git.door43.org/unfoldingWord/hbo_uhb), should be ignored by tC.  

See discussion: https://unfoldingword.zulipchat.com/#narrow/stream/212547-SOFTWARE.2FtC/topic/tc-source-content-updater.20breakage

**Comment by RobH123** [comment] 2020-03-10 19:33
Ideally it should handle book codes in https://ubsicap.github.io/usfm/master/identification/books.html differently from those that are not in there, i.e., ignore unneeded but valid book codes, but flag wrong book codes.

**Comment by birchamp** [comment] 2020-05-01 13:39
@jag3773 Can we move this to 2.3?

**Comment by jag3773** [comment] 2020-05-01 15:37
The specific issue here may best be looped into #4401 .  If tC supported the standard USFM front matter page (A0-FRT.usfm), we could put the copyright page information in that file, as well as other introductory information which would be useful for many translations.

Maybe that doesn't help answer your question?

**Comment by PhotoNomad0** [comment] 2020-07-25 10:55
Looks like the problem is here: https://github.com/unfoldingWord/tc-source-content-updater/blob/develop/src/helpers/packageParseHelpers.js#L127

Probably change this so that rather than throw an exception it will just warn.

**Comment by PhotoNomad0** [comment] 2020-07-28 16:19
Verified fix is in translationCore 3.0.0 (5a7caea)

**Comment by cckozie** [comment] 2020-08-05 18:18
There is no way to test this at this time.

**Comment by RobH123** [comment] 2020-08-05 20:05
Well, presumably if all current tests pass, that itself is a test that this change didn't mess up anything. So that half of the test has passed. But yes, now that the code is in there, hopefully it allows the content to test the inclusion of a front matter book when ready. Thanks.

**Closed as completed** 2022-08-18 13:03 UTC
Labels: QA/None
