### ISSUE TITLE
Unable to display es as GL in tW. Spanish(es-149) resources needs a name fix 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/translationCore#6436] opened 2019-09-16 15:37 UTC
2.0.0 (4b3ebee)

I downloaded the resources for Spanish ( es-419). After the download, the resources folder shows up as es-149 as in the snapshot:
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/6fe7f9e1-1a3f-40af-b4f2-e54f98f16673)

![image](https://user-images.githubusercontent.com/8171759/65884749-fe09d900-e35e-11e9-9c47-9f804cbc9658.png)

Due to this, Es is not available in the GL drop-down for Spanish Projects.

**Comment by cckozie** [comment] 2019-09-30 14:00
The problem is actually in the resource's manifest in the catalog where the identifier is wrong in https://git.door43.org/Door43-Catalog/es-419_tw/src/branch/master/manifest.yaml

<img width="593" alt="es-149" src="https://user-images.githubusercontent.com/8171759/65885565-8046cd00-e360-11e9-85fd-defbfc920f6a.png">

**Comment by PhotoNomad0** [comment] 2019-11-12 19:42
Created a PR against catalog https://git.door43.org/STR/es-419_tw/pulls/1

**Comment by PhotoNomad0** [comment] 2019-11-12 23:50
@cckozie PR has been merged.  Now need to wait for the Door43  catalog to be updated.  Could this go in QA watch?

**Comment by cckozie** [comment] 2019-11-13 04:04
@PhotoNomad0 - I'll move to In QA and put a hold on it.

**Comment by cckozie** [comment] 2019-11-13 04:04
Waiting for catalog to be updated.

**Comment by jag3773** [comment] 2019-11-13 16:07
Catalog should be updated at this point.

**Comment by cckozie** [comment] 2019-11-13 17:18
This problem was fixed by the catalog update.

**Closed as completed** 2019-12-19 20:30 UTC
Labels: QA/Pass, Kind/GLContent, QA/ElsyTested, Hotfix issue
