### ISSUE TITLE
USFM.js: Preserve data/markers outside of verses from an imported USFM file when exporting

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/translationCore#3209] opened 2017-11-16 18:59 UTC
USFM imports to tC have data/markers that occurs outside of a verse and are not currently preserved in any way. We don't currently have a use case for them inside of tC other than upon export. In order to preserve them upon export, we need to send the original imported USFM file to the JSON to USFM converter to preserve everything not in a verse, as the verse should already preserve what was imported.

We do not need to preserve the data for anything other than while exporting at this point.

**Comment by PhotoNomad0** [comment] 2017-11-21 13:11
## Tasks (TDD):

- [ ] [8] Write test cases to preserve USFM data outside of verses on import
- [ ] [8] Write test cases to preserve USFM data outside of verses on export

**Comment by PhotoNomad0** [comment] 2017-11-26 13:01
Note:  New format for verses json:

https://team43.slack.com/files/U0DRQNLAW/F7VSJ6CHM/Verse_Objects_Proposal.js


[
  { tag: 'w', type: 'word', text: 'Jesus', attributes: '...' },
  { type: 'text', text: ', ' },
  { tag: 'w', type: 'word', text: 'wept', attributes: '...' },
  { type: 'text', text: '.' },
  { tag: 'f', type: 'footnote', text: 'Here is a foot note that needs to be preserved but not words in the verse.' }
]

// An actual example:
{
  "1": {
    "1": [
      {
        "tag": "w",
        "type": "word",
        "text": "the book of",
        "aligned-text": "βίβλος",
        "aligned-occurrence": "1/1",
        "text-occurrence": "1/1"
      },
      {
        "tag": "w",
        "type": "word",
        "text": "the genealogy of",
        "aligned-text": "γενέσεως",
        "aligned-occurrence": "1/1",
        "text-occurrence": "1/1"
      },
      {
        "tag": "w",
        "type": "word",
        "text": "Jesus",
        "aligned-text": "ἰησοῦ",
        "aligned-occurrence": "1/1",
        "text-occurrence": "1/1"
      },
      {
        "tag": "w",
        "type": "word",
        "text": "Christ",
        "aligned-text": "χριστοῦ",
        "aligned-occurrence": "1/1",
        "text-occurrence": "1/1"
      },
      {
        "tag": "w",
        "type": "word",
        "text": "son of",
        "aligned-text": "υἱοῦ",
        "aligned-occurrence": "1/2",
        "text-occurrence": "1/2"
      },
      {
        "tag": "w",
        "type": "word",
        "text": "David",
        "aligned-text": "δαυεὶδ",
        "aligned-occurrence": "1/1",
        "text-occurrence": "1/1"
      },
      {
        "type": "text",
        "text": ","
      },
      {
        "tag": "w",
        "type": "word",
        "text": "son of",
        "aligned-text": "υἱοῦ",
        "aligned-occurrence": "2/2",
        "text-occurrence": "2/2"
      },
      {
        "tag": "w",
        "type": "word",
        "text": "Abraham",
        "aligned-text": "ἀβραάμ",
        "aligned-occurrence": "1/1",
        "text-occurrence": "1/1"
      },
      {
        "type": "text",
        "text": "."
      },
      {
        "tag": "f",
        "type": "footnote",
        "text": "This is a footnote about this verse, It shouldn't be rendered inline with the text."
      }
    ]
  }
}

**Comment by cckozie** [comment] 2017-12-15 22:00
0.8.1-alpha.13-4ef6c94 
Footnotes do not appear in exported USFM files. I get the same result whether importing USFM or tstudio/Door43.
Imported file:
[en_EPH_Ephesians-D.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1564114/en_EPH_Ephesians-D.usfm.zip)
https://git.door43.org/qa99/en_eph_text_reg
Exported files:
[en_eph.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1564117/en_eph.usfm.zip)

**Comment by klappy** [comment] 2017-12-20 16:25
@PhotoNomad0: We don't have this story implemented into tC itself do we? Wasn't this story to update the Library? I don't think that it can be tested until the other tasks to implement this into tC are completed.

**Comment by PhotoNomad0** [comment] 2017-12-23 20:05
@klappy - yes this is to update the library for USFM3 support.

**Comment by PhotoNomad0** [comment] 2017-12-27 14:38
#### Status:
waiting for USFM3 migration.

**Comment by cckozie** [comment] 2018-01-13 16:27
0.8.1-alpha.13-6dfca4e
Footnotes do not appear in USFM exports. It still looks like USFM2.

**Comment by PhotoNomad0** [comment] 2018-02-05 14:42
Need to implement native storage of verse objects in project chapter json.

**Comment by klappy** [comment] 2018-02-07 18:29
I think there might need to be more work done to this to add the original headers from the original USFM file that was imported.

**Comment by PhotoNomad0** [comment] 2018-02-12 12:38
#### Known issues:
https://github.com/unfoldingWord-dev/translationCore/issues/3758 - USFM import does not preserve all header info

**Comment by cckozie** [comment] 2018-02-20 20:47
Testing for preservation in USFM2 exports only. Other issue(s) will deal with USFM3 exports.

**Comment by cckozie** [comment] 2018-02-20 21:19
[53-1TH.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/1741902/53-1TH.usfm.zip)
Footnotes now appear in the word list in Word Alignment. (May be caused by the same problem I wrote up in #3758 of verse markers being displayed in the word list and scripture pane when the verse text is missing)
![image](https://user-images.githubusercontent.com/8171759/36449716-3c3fef8e-1651-11e8-8462-e4c075564b5c.png)

**Comment by PhotoNomad0** [comment] 2018-02-26 13:09
@cckozie - Yes this was caused by recent work.  Working on it.

**Comment by PhotoNomad0** [comment] 2018-02-26 14:11
@cckozie - Issue should be fixed now, but you will have to start over with fresh import of the project to clear out the old wordBank.

**Closed as completed** 2018-03-13 20:36 UTC
Labels: Epic, QA/Pass
