### ISSUE TITLE
Importing tstudio project reports the last verse as missing when it is not

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#3058] opened 2017-11-04 22:27 UTC
beta.96
[fr_tit_text_ulb.tstudio.zip](https://github.com/unfoldingWord-dev/translationCore/files/1443614/fr_tit_text_ulb.tstudio.zip)
This occurs both when importing from Door43 and locally.
It reports that 3:15 is missing, but it is in the project.
Maybe it's because 3:15 is the only verse in the chunk??

**Comment by PhotoNomad0** [comment] 2017-11-13 16:51
Tested with 0.8.1 on windows.  It is only showing error for missing verse at 1:1.
Was able to reproduce on Mac 0.8.1

**Comment by PhotoNomad0** [comment] 2017-11-13 16:52
- [ ] [4] Understand problem
- [ ] [4] Fix problem
- [ ] [4] Tests for Fix

**Comment by PhotoNomad0** [comment] 2017-11-13 17:09
It looks like this is fixed in the current develop branch.  Waiting for a build to verify.

**Comment by PhotoNomad0** [comment] 2017-11-17 18:33
@cckozie - Looks like this is working.  Tested 0.8.1-alpha 11 on Windows.

**Comment by cckozie** [comment] 2017-11-17 19:41
Works in 0.8.1-alpha.11

**Closed as completed** 2017-11-17 19:41 UTC
Labels: Kind/Bug, Epic, Priority/High
