### ISSUE TITLE
Validate rendering of complex scripts

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/translationCore#6788] opened 2020-03-25 13:45 UTC
Burmese and the MENA region have been identified as needing complex script support in tC.
For reference see #6879 and [SIL's Graphite demo page](https://scripts.sil.org/cms/scripts/page.php?site_id=projects&item_id=graphite_fontdemo)

For Burmese/Myanmar:
 - [Font files](https://software.sil.org/padauk/download/)
- [test project ](https://git.door43.org/birch/my_jud_tit_book), USFM file: [57-TIT_myanmar_judson_1835_utf8.usfm.txt](https://github.com/unfoldingWord/translationCore/files/4621965/57-TIT_myanmar_judson_1835_utf8.usfm.txt)
- incorrect rendering - the circle under the 3rd character should be a rounded triangle.
![gnome-shell-screenshot-NT85J0](https://user-images.githubusercontent.com/10272744/81813496-88b9d580-94f5-11ea-915a-bad0d68d1bdd.png)

**For MENA/Arabic/Urdu**
Awami Nastaliq
- Font: [Awami Nastaliq](https://software.sil.org/awami/)
   - sample USFM [86-TITarb-vd.usfm.txt](https://github.com/unfoldingWord/translationCore/files/4652089/86-TITarb-vd.usfm.txt)
  - Proper rendering - [Titus](https://drive.google.com/open?id=1Fin3mpw-YtRo8vRf0plxOkYGP6ZlsvFt) - Load font locally and open html file *locally* in Firefox
![Awami-Titus.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/97817fc7-9ff2-427f-bd85-edb242336a75)
   - [More files for testing](https://drive.google.com/drive/u/0/folders/1bsd5U-Mk2P_gyfjeg8g2c4AAZy3hgzAt)

Scheherazade
- Font [Scheherazade](https://software.sil.org/scheherazade/)
  - Sample USFM [86-TITarb-vd.usfm.txt](https://github.com/unfoldingWord/translationCore/files/4652089/86-TITarb-vd.usfm.txt)
  - Proper rendering - [Titus](https://drive.google.com/open?id=1e5pKW14ABdc0NEWpBn7N4lHv6qGICzJW) - Load font locally and open html file *locally* in Firefox
![Scheherazade-Titus.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/1a013d91-6099-4035-97ad-5acd5a482873)
  - [More files for testing](https://drive.google.com/drive/u/0/folders/1uOhSLmd_hZPaEBP76UdXbJxoxv8Ux1p9)

**Comment by birchamp** [comment] 2020-04-07 20:07
@jag3773 do you have contacts that can verify complex script rendering?

**Comment by jag3773** [comment] 2020-04-13 17:51
First test should be run against https://scripts.sil.org/cms/scripts/page.php?site_id=projects&item_id=graphite_fontdemo but If that passes I can send a screenshot for expert review.

**Comment by BincyJ** [comment] 2020-05-11 14:05
@birchamp to provide text for Burmese and Arabic to validate. We also need a way to confirm the rendering in tC. May need a tester / confirmation from a reader. 
Need confirmation on the scope of languages needed for Complex Script support release.

**Comment by birchamp** [comment] 2020-05-20 13:53
This issue is used for validating the work done for #6935

**Comment by cckozie** [comment] 2020-06-01 18:14
3.0.0 (c8646fa) 
**Alex verified that the rendering in tC and Paratext are both correct. The differences are caused by a difference in fonts.**
Comparing this screenshot from 1:2 in the https://git.door43.org/birch/ar_vdb_tit_book project to a screenshot taken from Paratext created from a USFM export of that project. 
(Paratext on top, tC on bottom of screenshots)
Paratext uses Charis SIL as the default font for the language, and Scheherazade is not in their dropdown font list.
There are some subtle and some more obvious differences. Are these acceptable? Are the differences caused by different fonts?
![image](https://user-images.githubusercontent.com/8171759/83439710-50792900-a409-11ea-8eaf-28138875d82c.png)

**Comment by cckozie** [comment] 2020-06-01 20:17
3.0.0 (c8646fa) 
The (my) font appears to be correctly rendered wherever it is displayed, but the font size is noticeably smaller in the edit pane of the expanded scripture pane (and from the tool bar in wA) than in the other panes where it is dispayed. (This 'problem' should be eliminated by the font sizing issue)
![image](https://user-images.githubusercontent.com/8171759/83451356-680ddd00-a41c-11ea-95fa-7f340e05e61b.png)

**Comment by cckozie** [comment] 2020-06-02 19:13
3.0.0 (c8646fa) 
https://git.door43.org/birch/ar_vdb_tit_book
[57-TIT_myanmar_judson_1835_utf8.usfm.txt.zip](https://github.com/unfoldingWord/translationCore/files/4719846/57-TIT_myanmar_judson_1835_utf8.usfm.txt.zip)

ISSUE A: **Fixed in 3.0.0 (a03e2cc)**
We are using a different font than the one selected when displaying the book name in the check pane of tN and tW, and in the verse edit pane for the scripture pane.
Before taking this screenshot I copied the book name into the beginning of the verse 1:1 text. The text in the two outlined boxes is the same but appears differently. This is with the Scheherazade font selected:
![image](https://user-images.githubusercontent.com/8171759/83559712-a8cc2b80-a4da-11ea-8bd4-213f5e120067.png)

This is with the Awami Nastaliq font selected:
![image](https://user-images.githubusercontent.com/8171759/83560030-298b2780-a4db-11ea-918e-a5d390e58422.png)
![image](https://user-images.githubusercontent.com/8171759/83678125-d8466b00-a5a2-11ea-9001-6cd92120b406.png)

ISSUE B: **Fixed in 3.0.0 (a03e2cc)**
The default font size is too large and the line spacing too small for the Awami Nastaliq font.

ISSUE C: (Questions)
There appears to be a problem with the tokenizer in Burmese, and maybe with word breaks too. Where we break words to line wrap seems to be almost arbitrary. Is that acceptable in Burmese?
![image](https://user-images.githubusercontent.com/8171759/83562584-71ac4900-a4df-11ea-81a0-36428dd76b7e.png)
![image](https://user-images.githubusercontent.com/8171759/83562930-0020ca80-a4e0-11ea-933e-e52f658918ba.png)

![image](https://user-images.githubusercontent.com/8171759/83572203-bdb2ba00-a4ee-11ea-81e3-baa6bd304151.png)

**Comment by birchamp** [comment] 2020-06-03 13:29
Issue C is good enough for now until we have a better Burmese text.

**Comment by cckozie** [comment] 2020-06-04 17:42
@mannycolon - I found a few other places with problems. One where the default font is being used; when hovering over a word in the word bank. Some with a sizing problems. Is it OK to leave them here, or would you rather that I create another issue for them (and maybe others that I may run across)?
ISSUE D: **Cannot test this now since the hover problems has been fixed**
![image](https://user-images.githubusercontent.com/8171759/83792428-adbae780-a660-11ea-9d66-f1d42d43e2bd.png)

ISSUE E: **Fixed in 3.0.0 (a03e2cc)**
![image](https://user-images.githubusercontent.com/8171759/83793345-05a61e00-a662-11ea-8bec-700c3a3fbd31.png)

ISSUE F:
![image](https://user-images.githubusercontent.com/8171759/83794401-96312e00-a663-11ea-99b5-59abe2affc75.png)

**Comment by mannycolon** [comment] 2020-06-04 18:15
@cckozie These are good for now, I will include them with the work I'm doing now.

**Comment by cckozie** [comment] 2020-06-04 18:31
@mannycolon 
ISSUE G: **Has not been fixed 3.0.0 (a03e2cc)**
Found another one. This is from clicking the expand pane icon in the check pane in tN. (It probably would be good to increase the size on this one too if that's just a simple setting)
![image](https://user-images.githubusercontent.com/8171759/83797071-a2b78580-a667-11ea-8192-35fa321130e4.png)

**Comment by mannycolon** [comment] 2020-06-07 21:59
Verified on cbed56b

**Comment by cckozie** [comment] 2020-06-08 14:56
3.0.0 (dad3c32)
ISSUE A: Both problems noted have been fixed except for the problem of the font used for the language abbreviation noted below.

ISSUE B: This problem has been fixed.

ISSUE C: N/A

ISSUE D: Unable to test in this build because the word bank hover-over is not working.

ISSUE E: Has been fixed

ISSUE F: Has been fixed.

ISSUE G: Has been fixed. I'm creating a new issue for the font size problem (#6978)

**Comment by cckozie** [comment] 2020-06-08 15:34
@mannycolon - I wrote this up here because I am assuming this problem was introduced by the fixes made for this issue. If that is not what cause it, I'll create a new issue for it.
[ar_test_rut_book.zip](https://github.com/unfoldingWord/translationCore/files/4746750/ar_test_rut_book.zip)
The font for the word Arabic and abbreviation (AR) has changed.  **Not** fixed in 3.0.0 (a03e2cc) **@birchamp - Are you OK with this?** Created issue #7025 for this if we want to change it.
The color of the text description (target, orignal, gateway, etc.) has changed. I think it now may also be bolded. **Fixed in 3.0.0 (a03e2cc)**
This is from 3.0.0 (dad3c32)
![image](https://user-images.githubusercontent.com/8171759/84044934-d0eddb80-a96d-11ea-950e-30cd4628bef9.png)


This is from 3.0.0 (c8646fa) and previous:
![image](https://user-images.githubusercontent.com/8171759/84044510-4b6a2b80-a96d-11ea-870f-5d98ca00f97c.png)

**Comment by mannycolon** [comment] 2020-06-29 21:03
Verified on a03e2cc

**Closed as completed** 2020-07-21 13:10 UTC
Labels: QA/Pass, Priority/High, Electronite
