### ISSUE TITLE
Browse Door43 projects in tutorial

### ISSUE THREAD

**Issue by EllDoubleYew** [unfoldingWord/translationCore#97] opened 2016-09-07 22:16 UTC
> As a translation checker I want a way to load my project in from Door43 during my initial setup so that I can begin my checking more quickly and with less confusion.

This may find its easiest solution by housing the project browser inside of the welcome project upload modal but there are multiple ways to solve this problem.

**Comment by klappy** [comment] 2016-10-12 15:42
Duplicate of issue #199

**Closed as completed** 2016-10-20 18:33 UTC
Labels: Reviewed/Duplicate
